import os
import subprocess
from google import genai
from github import Github
from pathlib import Path

# ==============================
# Constants
# ==============================
BASE_BRANCH = "main"
AGENT_DIR = Path(".agent")
CLINE_RULES_PATH = Path(".clinerules")
README_PATH = Path("README.md")

# ==============================
# Environment
# ==============================
issue_title = os.environ["ISSUE_TITLE"]
issue_body = os.environ["ISSUE_BODY"]
issue_number = os.environ["ISSUE_NUMBER"]
repo_name = os.environ["REPO"]

# ==============================
# Utilities
# ==============================
def load_text(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    return path.read_text(encoding="utf-8")

def run(cmd):
    subprocess.run(cmd, check=True)

# ==============================
# Load canonical documents
# ==============================
cline_rules = load_text(CLINE_RULES_PATH)
readme = load_text(README_PATH)

base_prompt = load_text(AGENT_DIR / "prompt.txt")

# ==============================
# Prompt composition
# ==============================
prompt = f"""
{cline_rules}

================================
【Repository Design (README.md)】
================================
{readme}

================================
【Agent Role】
================================
{base_prompt}

================================
【Task】
================================
{issue_title}

================================
【Details】
================================
{issue_body}

================================
【Output Format (STRICT)】
================================
Your output must follow this exact structure:
1. Commit message (following .clinerules)
2. A line containing exactly "---DIFF_START---"
3. The unified diff

Example:
feat(auth): refresh token automatically

Design:
- Chosen: ...
- Rejected: ...
- Reason: ...

Impact:
- Affected modules: ...
- Behavior change: ...

Test:
- Added: ...
- Not added: ...

---DIFF_START---
diff --git a/src/file.js b/src/file.js
...
"""

# ==============================
# Gemini
# ==============================
client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
response = client.models.generate_content(
    model="gemini-1.5-flash",
    contents=prompt
)
output = response.text.strip()

if "---DIFF_START---" not in output:
    raise RuntimeError("Model output does not contain ---DIFF_START---")

commit_message, patch = output.split("---DIFF_START---", 1)
commit_message = commit_message.strip()
patch = patch.strip()

# Remove markdown code block markers if present
if patch.startswith("```"):
    # Remove first line (e.g. ```diff)
    lines = patch.splitlines()
    if lines[0].startswith("```"):
        lines = lines[1:]
    # Remove last line if it's ```
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]
    patch = "\n".join(lines).strip()

if not patch.startswith("diff"):
    # Try to find the start of diff if there's any garbage (like leading text or markers)
    idx = patch.find("diff")
    if idx == -1:
        raise RuntimeError(f"Model output does not contain a valid unified diff. Output: {output[:200]}...")
    patch = patch[idx:]

# Ensure patch does not end with markdown marker
if patch.endswith("```"):
    patch = patch[:-3].strip()

# ==============================
# Git: config & create branch
# ==============================
run(["git", "config", "user.name", "github-actions[bot]"])
run(["git", "config", "user.email", "github-actions[bot]@users.noreply.github.com"])

branch = f"agent/issue-{issue_number}"
# Create branch or reset if exists
subprocess.run(["git", "checkout", "-B", branch], check=True)

# ==============================
# Apply patch
# ==============================
patch_path = AGENT_DIR / "change.diff"
patch_path.write_text(patch, encoding="utf-8")

run(["git", "apply", str(patch_path)])

# ==============================
# Commit & push
# ==============================
run(["git", "add", "."])
run([
    "git",
    "commit",
    "-m",
    commit_message
])
run(["git", "push", "-u", "origin", branch])

# ==============================
# Create PR
# ==============================
gh = Github(os.environ["GITHUB_TOKEN"])
repo = gh.get_repo(repo_name)

pr = repo.create_pull(
    title=f"[Agent] {issue_title}",
    body=(
        "Auto-generated by Gemini\n\n"
        f"Closes #{issue_number}\n\n"
        "Rules: .clinerules\n"
        "Design: README.md"
    ),
    head=branch,
    base=BASE_BRANCH
)

print(pr.html_url)
